src/webWhyPark/Models/LoginCliente.cs
using System.Reflection.Emit;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data;
using Microsoft.EntityFrameworkCore;

namespace webWhyPark.Models
{
    public class LoginCliente
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Obrigatório informar o email!")]
        public string Email { get; set; } = null!;

        [Display(Name = "Senha")]
        [Required(ErrorMessage = "Obrigatório informar uma senha!")]
        public string Senha { get; set; } = null!;

    }

}

src/webWhyPark/Controllers/LoginClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webWhyPark.Context;
using webWhyPark;
using webWhyPark.Models;
using System;
using System.Security.Claims;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace webWhyPark.Controllers
{
    public class LoginClienteController : Controller
    {
        private readonly ApplicationDbContext _context = null!;


        //Construtor do Login do Cliente no Contexto
        public LoginClienteController(ApplicationDbContext context)
        {
            if (context != null)
                _context = context;
        }

        //Criar rota do Login do Cliente

        //GET LoginCliente/Login
        public IActionResult Login(bool errLogin)
        {
            if (errLogin)
            {
                ViewBag.Erro = "Nickname e/ou senha estão incorretos";
            }
            return View();
        }


        [HttpPost, AllowAnonymous]
        public async Task<IActionResult> Login([Bind("Email,Senha")] Cliente cliente)
        {


            var client = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Email == cliente.Email);
            if (cliente?.Email == "" || client == null)
            {
                TempData["erroMensage"] = "Email ou senha não cadastrada !";
                return RedirectToAction("Login");
            }


            bool senhaValida = BCrypt.Net.BCrypt.Verify(cliente?.Senha, client?.Senha);

            if (client?.Email == cliente?.Email && senhaValida)
            {
                TempData["Nome"] = client?.Nome;
                await new Services().Login(HttpContext, client!);
                return RedirectToAction("Profile");
            }
            else
            {
                TempData["erroMensage"] = "Email ou senha não cadastrada !";
                return RedirectToAction("Login");

            }

        }


        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await new Services().Logout(HttpContext);
            return Redirect("~/Home/Index");

        }

        [Authorize(Roles = "cliente")]
        public IActionResult Profile()
        {
            ViewBag.Permissoes = HttpContext.User.Claims.Where(x => x.Type == ClaimTypes.Role).Select(x => x.Value);
            return View();
        }

        public IActionResult AcessDenied()
        {
            return View();
        }

        //Get: LoginCliente
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        //Get: LoginCliente/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loginCli = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loginCli == null)
            {
                return NotFound();
            }
            return View(loginCli);
        }


    }
}

src/webWhyPark/Controllers/VeiculoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webWhyPark.Context;
using webWhyPark.Models;
using System;
using System.Security.Claims;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webWhyPark.Controllers
{
    public class VeiculoController : Controller
    {
        private readonly ApplicationDbContext _context = null!;


        //Construtor do Cadastro do Veiculo no Contexto
        public VeiculoController(ApplicationDbContext context)
        {
            if (context != null)
                _context = context;
        }

        //Index 
        //GET: Veiculo
        public async Task<IActionResult> Index()
        {
            return View(await _context.Veiculos.ToListAsync());
        }

        //GET: Veiculos/Details/2
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Recupera o Veiculo

            var veiculoCadastrado = await _context.Veiculos
                                .FirstOrDefaultAsync(e => e.Id == id);

            if (veiculoCadastrado == null)
            {
                return NotFound();
            }

            return View(veiculoCadastrado);

        }

        //Criar rota do Cadastro do Veiculo
        //GET Veiculo/Create

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Placa,Cor,Modelo,Veiculo")] Veiculo veiculoCadastrado)
        {
            if (ModelState.IsValid)
            {

                _context.Add(veiculoCadastrado);
                await _context.SaveChangesAsync();
                return Redirect("/");
            }
            return View();
        }

        //Recupera o Veiculo para editar
        //GET: Veiculo/Edit/9

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var veiculoCadastrado = await _context.Veiculos.FindAsync(id);

            if (veiculoCadastrado == null)
            {
                return NotFound();
            }

            return View(veiculoCadastrado);
        }

        //POST Veiculo/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Placa,Cor,Modelo,Veiculo")] Veiculo veiculoCadastrado)
        {
            if (id != veiculoCadastrado.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

                try
                {
                    _context.Veiculos.Update(veiculoCadastrado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VeiculoExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(/*especificarCaminho*/);
            }

            return View(veiculoCadastrado);
        }

        //Recupera o Veiculo para deletar
        //GET: Veiculo/Delete/9
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var veiculoCadastrado = await _context.Veiculos
                                .FirstOrDefaultAsync(d => d.Id == id);

            if (veiculoCadastrado == null)
            {
                return NotFound();
            }

            return View(veiculoCadastrado);
        }

        //POST Veiculo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var veiculoCadastrado = await _context.Veiculos.FindAsync(id);
            _context.Veiculos.Remove(veiculoCadastrado!);
            await _context.SaveChangesAsync();
            return RedirectToAction(/*especificarCaminho*/);
        }
        public bool VeiculoExists(int id)
        {
            return _context.Veiculos.Any(e => e.Id == id);
        }



    }
}

src/webWhyPark/Views/LoginCliente/AcessDenied.cshtml
@{
    ViewData["Title"] = "Acesso negado";
}

<h1>Você não tem permissão de acessar este recurso!</h1>

src/webWhyPark/Views/LoginCliente/Login.cshtml
@model webWhyPark.Models.Cliente

@{
    ViewData["Title"] = "Efetuar login";

    <style scoped>
        .body {
            margin: 0;
        }

        body * {
            box-sizing: border-box;
        }

        .main-login {
            width: 100vw;
            height: 100vh;
            background: rgb(63, 60, 60);
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .left-login {
            width: 50vw;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        .left-login>h1 {
            font-size: 3vw;
            color: rgb(209, 205, 205);
        }

        .right-login {
            width: 50vw;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .card-login {
            width: 60%;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            padding: 30px 35px;
            background: rgb(86, 85, 85);
            border-radius: 20px;
            box-shadow: 0px 10px 40px rgba(0, 0, 0, 0.335);
        }

        .card-login>h1 {
            color: rgb(209, 205, 205);
            font-weight: 800;
            margin: 0;
        }

        .textfield {
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            margin: 10px 0px;
        }

        .textfield>input {
            width: 100%;
            border: none;
            border-radius: 10px;
            padding: 15px;
            background: whitesmoke;
            font-size: 12pt;
            box-shadow: 0px 10px 40px rgba(0, 0, 0, 0.335);
            outline: none;
            box-sizing: border-box;
        }

        .textfield>label {
            color: white;
            margin-bottom: 10px;
        }

        .btn-login {
            width: 50%;
            padding: 16px 0px;
            margin: auto;
            border: none;
            border-radius: 8px;
            outline: none;
            text-transform: uppercase;
            text-decoration: none;
            text-align: center;
            font-weight: 800;
            color: black;
            background: lightgray;
            cursor: pointer;
            box-shadow: 0px 10px 4px -12px #0000005a;
        }

        .left-login-image {
            height: 520px;
        }
    </style>
}

<body>

    <div class="main-login">
        <div class="left-login">
            <h1>Já possui cadastro?<br>Faça o seu login!</h1>
            <img src="/../imagens/carro.svg" class="left-login-image" alt="carro">
        </div>
        <div class="right-login">
            <div class="card-login">
                <h1 class="fs-1">Login</h1>
                <form asp-action="Login" class="w-75">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="textfield">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                 
                    <div class="textfield">
                        <label asp-for="Senha" class="control-label"></label>
                        <input asp-for="Senha" type="password" />
                        <span asp-validation-for="Senha" class="text-danger"></span>
                    </div>
                    <div class="textfield align-text-center">
                         <span class="text-danger"> @TempData["erroMensage"]</span> 
                    </div>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        @* <a class="btn-login" asp-controller="Home" asp-action="Index">Voltar</a> *@
                        <input type="submit" value="Entrar" class="btn-login mt-3" />
                    </div>
                </form>
            </div>
        </div>

</body>

<hr />
</div>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/webWhyPark/Views/LoginCliente/Profile.cshtml
@model IEnumerable<webWhyPark.Models.Cliente>


@{
    ViewData["Title"] = "Perfil do Cliente";

    <style scoped>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        :root {
            --gray: rgb(209, 205, 205);
            --darkgray: rgb(63, 60, 60);
            --lightgray: rgb(245, 245, 245);
            --white: rgb(255, 255, 255);
            --grayDetaisCard: rgba(96, 96, 96, 0.8);
        }

        body {
            min-height: 100vh;
            overflow-x: hidden;
        }

        .container {
            position: relative;
            width: 100%;
        }

        .navigation {
            position: fixed;
            left: 0%;
            width: 300px;
            height: 100%;
            background: var(--gray);
            border-left: 5px solid var(--gray);
            transition: 0.5s;
            overflow: hidden;
        }

        .navigation.active {
            width: 80px;
            transition: 0.5s;
        }

        .navigation ul {
            position: absolute;
            top: 10px;
            left: -20px;
            width: 100%;
        }

        .navigation ul li {
            position: relative;
            width: 100%;
            list-style: none;
            border-top-left-radius: 10px;
            border-bottom-left-radius: 10px;
        }

        .navigation ul li:hover,
        .navigation ul li.hovered {
            background: var(--lightgray);
        }

        .navigation ul li:nth-child(1) {
            margin-bottom: 40px;
            pointer-events: none;
        }

        .navigation ul li a {
            position: relative;
            display: block;
            width: 100%;
            display: flex;
            text-decoration: none;
            color: var(--darkgray);
        }

        .navigation ul li:hover a .navigation ul li.hovered a {
            color: var(--gray);
        }

        .navigation ul li a .icon {
            position: relative;
            display: block;
            min-width: 60px;
            height: 60px;
            line-height: 75px;
            text-align: center;
        }

        .navigation ul li a .icon ion-icon {
            font-size: 1.75em;
        }

        .navigation ul li a .title {
            position: relative;
            display: block;
            padding: 0 10px;
            height: 60px;
            line-height: 60px;
            text-align: start;
            white-space: nowrap;
            font-weight: 500;
        }

        @*Curvaparaoalto*@.navigation ul li:hover a::before,
        .navigation ul li.hovered a::before {
            content: '';
            position: absolute;
            right: -20px;
            top: -60px;
            width: 60px;
            height: 60px;
            background: transparent;
            border-radius: 50%;
            box-shadow: 35px 35px 0 10px var(--lightgray);
            pointer-events: none;
        }

        @*Curvaparabaixo*@.navigation ul li:hover a::after,
        .navigation ul li.hovered a::after {
            content: '';
            position: absolute;
            right: -20px;
            bottom: -60px;
            width: 60px;
            height: 60px;
            background: transparent;
            border-radius: 50%;
            box-shadow: 46px -35px 0 10px var(--lightgray);
            pointer-events: none;
        }

        @*Main*@.main {
            position: absolute;
            width: calc(100% - 300px);
            left: 300px;
            min-height: 100vh;
            background: var(--lightgray);
            transition: 0.5s;
        }

        .main.active {
            width: calc(100% - 80px);
            left: 80px;
        }

        .topbar {
            width: 100%;
            height: 60%;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 10px;
        }

        .toggle {
            position: relative;
            top: 0;
            width: 60px;
            height: 60px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 2.5em;
            cursor: pointer;
        }

        .search {
            position: relative;
            width: 400px;
            margin: 0 10px;
        }

        .search label {
            position: relative;
            width: 100%;
        }

        .search label input {
            width: 100%;
            height: 40px;
            border-radius: 40px;
            padding: 5px 20px;
            padding-left: 35px;
            font-size: 18px;
            outline: none;
            border: 1px solid var(--darkgray);
        }

        .search label ion-icon {
            position: absolute;
            top: 10px;
            left: 10px;
            font-size: 1.4em;
        }

        @*ImagemUsuário*@.user {
            position: relative;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            overflow: hidden;
            cursor: pointer;
        }

        .user img {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        @*Cards*@.cardBox {
            position: relative;
            width: 100%;
            padding: 20px;
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            grid-gap: 20px;
        }

        .cardBox .card {
            position: relative;
            background: var(--white);
            padding: 30px;
            border-radius: 8px;
            display: flex;
            justify-content: space-between;
            cursor: pointer;
            box-shadow: 0 7px 25px rgb(0, 0, 0, 0.1);
        }

        .cardBox .card .numbers {
            position: relative;
            font-weight: 500;
            font-size: 2.5em;
            color: var(--grayDetaisCard);
        }

        .cardBox .card .cardName {
            color: var(--grayDetaisCard);
            font-size: 1.1em;
            margin-top: 5px;
        }

        .cardBox .card .iconBox {
            font-size: 3.5em;
            color: var(--grayDetaisCard)
        }

        .cardBox .card:hover {
            background: var(--gray);
        }

        .cardBox .card:hover .numbers,
        .cardBox .card:hover .cardName,
        .cardBox .card:hover .iconBox {
            color: var(--white);
        }
    </style>
}




<body>

    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="person-circle-outline"></ion-icon>
                        </span>
                        <span class="title"> @TempData["Nome"]</span>
                    </a>
                </li>
                <li onclick="gerFunction()">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="settings-outline"></ion-icon>
                        </span>
                        <span class="title">Gerenciar conta</span>
                    </a>
                </li>
                <li onclick="cadVeiculos()">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="mail-outline"></ion-icon>
                        </span>
                        <span class="title" asp-area="" asp-controller="Veiculo" asp-action="Create"
                            asp-action="Privacy">Cadastrar Veículos</span>
                    </a>
                </li>
                <li onclick="historico()">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="file-tray-full-outline"></ion-icon>
                        </span>
                        <span class="title">Histórico</span>
                    </a>
                </li>
                <li onclick="favoritos()">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="star-outline"></ion-icon>
                        </span>
                        <span class="title">Favoritos</span>
                    </a>
                </li>
                <li onclick="mesagem()">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="mail-outline"></ion-icon>
                        </span>
                        <span class="title">Mensagens</span>
                    </a>
                </li>
                <li onclick="info()">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="information-circle-outline"></ion-icon>
                        </span>
                        <span class="title">Ajuda</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Logout">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sair</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    @* Main *@
    <div class="main">
        <div class="topbar">
            <div class="toggle">
                <ion-icon name="menu-outline"></ion-icon>
            </div>
            @* Pesquisar *@
            <div class="search">
                <label>
                    <input type="text" placeholder="Pesquisar">
                    <ion-icon name="search-outline"></ion-icon>
                </label>
            </div>
            @* Imagem de Usuário *@
            <div class="user">
                <img src="/../imagens/batman.jpg" alt="usuario">
            </div>
        </div>

        <div id="gerenciar">
            @* Cards *@
            <div class="cardBox">
                <div class="card">
                    <div>
                        <div class="numbers">12</div>
                        <div class="cardName">Paradas</div>
                    </div>
                    <div class="iconBox">
                        <ion-icon name="car-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">4</div>
                        <div class="cardName">Favoritos</div>
                    </div>
                    <div class="iconBox">
                        <ion-icon name="star-outline"></ion-icon>
                    </div>
                </div>
                <div class="card">
                    <div>
                        <div class="numbers">1</div>
                        <div class="cardName">Mensagem</div>
                    </div>
                    <div class="iconBox">
                        <ion-icon name="chatbubbles-outline"></ion-icon>
                    </div>
                </div>


                <div>


                </div>

            </div>
        </div>

        <div id="cadVeiculo" class="w-100" >
            <div class="w-100 d-flex  align-items-center border-black" >
            <div class="form-control p-4 w-50">
                <div class="form-row form d-flex">
                <h1>Cadastre o veículo</h1>

                    <div class="col-md-4 mb-3">
                        <label for="validationDefault01">Placa</label>
                        <input type="text" class="form-control" id="validationDefault01" placeholder="" value=""
                            required>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="validationDefault02">Cor</label>
                        <input type="text" class="form-control" id="validationDefault02" placeholder="" value=""
                            required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="validationDefault03">Modelo</label>
                        <input type="text" class="form-control" id="validationDefault03" placeholder="" required>
                    </div>
                    </label>
            <button class="btn btn-secondary" type="submit">Enviar</button>
                </div>
        </div>
        </div>
        </div>
    </div>

    <div id="historico">
        historico
    </div>

    <div id="favorito">
        Favoritos
    </div>

    <div id="msg">
        Mensagens
    </div>

    <div id="help">
        Ajuda
    </div>








    @*Ícones*@
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


</body>

@*
    @Html.ActionLink("Fazer Logoff","Logout");*@

@* @foreach (var perm in ViewBag.Permissoes)
    {
    <p>Cargo:<u>@perm</u></p>
    }
*@