src/webWhyPark/Controllers/CadastroClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webWhyPark.Context;
using webWhyPark.Models;
using System;
using System.Security.Claims;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webWhyPark.Controllers
{
    public class CadastroClienteController : Controller
    {
        private readonly ApplicationDbContext _context = null!;


        //Construtor do Cadastro do Cliente no Contexto
        public CadastroClienteController(ApplicationDbContext context)
        {
            if (context != null)
                _context = context;
        }

        //Index 
        //GET: CadastroCliente
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        //GET: CadastroClientes/Details/2
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Recupera o Cliente

            var cadastroCli = await _context.Clientes
                                .FirstOrDefaultAsync(e => e.Id == id);

            if (cadastroCli == null)
            {
                return NotFound();
            }

            return View(cadastroCli);

        }

        //Criar rota do Cadastro do Cliente
        //GET CadastroCliente/Create

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Email,Senha")] Cliente cadastroCli)
        {
            if (ModelState.IsValid)
            {
                cadastroCli.Senha = BCrypt.Net.BCrypt.HashPassword(cadastroCli.Senha, BCrypt.Net.SaltRevision.Revision2B);
                _context.Add(cadastroCli);
                await _context.SaveChangesAsync();
                return Redirect("~/LoginCliente/Login");
            }
            return View();
        }

        //Recupera o CadastroCliente para editar
        //GET: CadastroCliente/Edit/9

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroCli = await _context.Clientes.FindAsync(id);

            if (cadastroCli == null)
            {
                return NotFound();
            }

            return View(cadastroCli);
        }

        //POST CadastroCliente/Delete/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Email,Senha")] Cliente cadastroCli)
        {
            if (id != cadastroCli.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

                try
                {
                    _context.Clientes.Update(cadastroCli);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CadastroClienteExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(cadastroCli);
        }

        //Recupera o CadastroCliente para deletar
        //GET: CadastroCliente/Edit/9
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroCli = await _context.Clientes
                                .FirstOrDefaultAsync(d => d.Id == id);

            if (cadastroCli == null)
            {
                return NotFound();
            }

            return View(cadastroCli);
        }

        //POST CadastroCliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var cadastroCli = await _context.Clientes.FindAsync(id);
            _context.Clientes.Remove(cadastroCli!);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public bool CadastroClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }



    }
}

src/webWhyPark/Controllers/EstacionamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webWhyPark.Context;
using webWhyPark.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webWhyPark.Controllers
{
    public class EstacionamentoController : Controller
    {

        private readonly ApplicationDbContext _context = null!;

        //Constructor
        public EstacionamentoController(ApplicationDbContext context)
        {
            if (context != null)
                _context = context;
        }


        //Index
        //GET: Estacionamentos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estacionamentos.ToListAsync());
        }

        //GET: Estacioanamentos/Details/2
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Recupera o estacionamento

            var estacionamento = await _context.Estacionamentos
                                .FirstOrDefaultAsync(e => e.Id == id);

            if (estacionamento == null)
            {
                return NotFound();
            }

            return View(estacionamento);

        }


        //Criar estacionameto rota
        //GET Estacionamento/Create

        public IActionResult Create()
        {
            return View();
        }



        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("Id,RazaoSocial,CNPJ,Telefone,Email,Senha")] Estacionamento estacionamento)
        {
            if (ModelState.IsValid)
            {
                estacionamento.Senha = BCrypt.Net.BCrypt.HashPassword(estacionamento.Senha, BCrypt.Net.SaltRevision.Revision2B);
                _context.Add(estacionamento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        //Recupera o estacionamento para editar
        //GET: Estacionamento/Edit/9

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estacionamento = await _context.Estacionamentos.FindAsync(id);

            if (estacionamento == null)
            {
                return NotFound();
            }

            return View(estacionamento);
        }

        //POST Estacionamento/Delete/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("Id,RazaoSocial,CNPJ,Telefone,Email")] Estacionamento estacionamento)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    _context.Estacionamentos.Update(estacionamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstacionamentoExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(estacionamento);
        }


        //Recupera o estacionamento para deletar
        //GET: Estacionamento/Edit/9

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estacionamento = await _context.Estacionamentos
                                .FirstOrDefaultAsync(d => d.Id == id);

            if (estacionamento == null)
            {
                return NotFound();
            }

            return View(estacionamento);
        }

        //POST Estacionamento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var estacionamento = await _context.Estacionamentos.FindAsync(id);
            _context.Estacionamentos.Remove(estacionamento!);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public bool EstacionamentoExists(int id)
        {
            return _context.Estacionamentos.Any(e => e.Id == id);
        }
    }
}

src/webWhyPark/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using webWhyPark.Models;

namespace webWhyPark.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/webWhyPark/Controllers/LoginClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webWhyPark.Context;
using webWhyPark;
using webWhyPark.Models;
using System;
using System.Security.Claims;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace webWhyPark.Controllers
{
    public class LoginClienteController : Controller
    {
        private readonly ApplicationDbContext _context = null!;


        //Construtor do Login do Cliente no Contexto
        public LoginClienteController(ApplicationDbContext context)
        {
            if (context != null)
                _context = context;
        }

        //Criar rota do Login do Cliente

        //GET LoginCliente/Login
        public IActionResult Login(bool errLogin)
        {
            if (errLogin)
            {
                ViewBag.Erro = "Nickname e/ou senha estão incorretos";
            }
            return View();
        }


        [HttpPost, AllowAnonymous]
        public async Task<IActionResult> Login([Bind("Email,Senha")] Cliente cliente)
        {


            var client = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Email == cliente.Email);
            if (cliente?.Email == "" || client == null)
            {
                TempData["erroMensage"] = "Email ou senha não cadastrada !";
                return RedirectToAction("Login");
            }


            bool senhaValida = BCrypt.Net.BCrypt.Verify(cliente?.Senha, client?.Senha);

            if (client?.Email == cliente?.Email && senhaValida)
            {
                TempData["Nome"] = client?.Nome;
                await new Services().Login(HttpContext, client!);
                return RedirectToAction("Profile");
            }
            else
            {
                TempData["erroMensage"] = "Email ou senha não cadastrada !";
                return RedirectToAction("Login");

            }

        }


        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await new Services().Logout(HttpContext);
            return Redirect("~/Home/Index");

        }

        [Authorize(Roles = "cliente")]
        public IActionResult Profile()
        {
            ViewBag.Permissoes = HttpContext.User.Claims.Where(x => x.Type == ClaimTypes.Role).Select(x => x.Value);
            return View();
        }

        public IActionResult AcessDenied()
        {
            return View();
        }

        //Get: LoginCliente
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        //Get: LoginCliente/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loginCli = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loginCli == null)
            {
                return NotFound();
            }
            return View(loginCli);
        }


    }
}

src/webWhyPark/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
  <style scoped>
    section {
      width: 100%;
      height: calc(100vh - 124px);
      background-image: url("../imagens/home.jpg");
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      display: flex;
      align-items: center;
      justify-content: start;
      flex-direction: column;
    }

    textarea:focus,
    input:focus,
    select:focus {
      box-shadow: 0 0 0 0 !important;
      border: 0 none !important;
      outline: 0 !important;
    }
  </style>
}
<header>

  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light   box-shadow "
    style="background-color: #000000;">
    <div class="container-fluid">
      <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">WhyPark</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">

        </ul>
        <ul class="navbar-nav mr-auto mx-2 d-flex align-items-center">
          <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="Estacionamento" asp-action="Index"
              asp-action="Privacy">Estacionamento</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link text-light px-4" asp-area="" asp-controller="CadastroCliente" asp-action="Create"
              asp-action="Privacy">Criar conta</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light rounded border-2 btn btn-primary bg-transparent border-white px-4" asp-area=""
              asp-controller="LoginCliente" asp-action="Login" asp-action="Privacy">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<main class="bg-dark">
  <section class="container-fluid">
    <figure class="text-center container" style="margin-bottom: 80px;">
      <blockquote class="blockquote py-4">
        <h1 class="text-white mt-4">WhyPark</h1>
      </blockquote>
      <blockquote class="blockquote text-light">
        O estacionamento mais próximo de você!
      </blockquote>
    </figure>

    <form class="form-control  rounded-pill w-50 p-0 ml-0 d-flex align-items-center justify-content-center flex-row"
      style="height: 50px;">
      <div class=" bg-white px-2  rounded-pill" style="margin-left:10px ;"><i class="fa fa-map-marker"
          style="font-size:26px"></i>

      </div>
      <input class="form-control outline-none border-0 w-100  h-100 " placeholder="Informe o endereço" />
      <button type="submit" class="px-5   btn  border-0 text-white rounded-pill "
        style="height: 50px; margin-right: -2px !important; background: #000000;"><i
          class=" 	fa fa-search"></i></button>
    </form>
    </div>
  </section>

</main>